//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs_EVE_Character_Tracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cs_EVE_Character_Tracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,#System
        ///2,Corporation
        ///3,Region
        ///4,Constellation
        ///5,Solar System
        ///6,Sun G5 (Yellow)
        ///7,Sun K7 (Orange)
        ///8,Sun K5 (Red Giant)
        ///9,Sun B0 (Blue)
        ///10,Sun F0 (White)
        ///11,Planet (Temperate)
        ///12,Planet (Ice)
        ///13,Planet (Gas)
        ///14,Moon
        ///15,Asteroid Belt
        ///16,Stargate (Caldari System)
        ///17,Stargate (Amarr Constellation)
        ///18,Plagioclase
        ///19,Spodumain
        ///20,Kernite
        ///21,Hedbergite
        ///22,Arkonor
        ///23,Cargo Container
        ///24,Ring
        ///25,Corpse
        ///26,Office Folder
        ///27,Office
        ///28,Factory Folder
        ///29,Credits
        ///30,Faction
        ///34,Tritanium
        ///35, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string invTypes {
            get {
                return ResourceManager.GetString("invTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2403,Advanced Planetology
        ///2406,Planetology
        ///2495,Interplanetary Consolidation
        ///2505,Command Center Upgrades
        ///3184,ORE Industrial
        ///3300,Gunnery
        ///3301,Small Hybrid Turret
        ///3302,Small Projectile Turret
        ///3303,Small Energy Turret
        ///3304,Medium Hybrid Turret
        ///3305,Medium Projectile Turret
        ///3306,Medium Energy Turret
        ///3307,Large Hybrid Turret
        ///3308,Large Projectile Turret
        ///3309,Large Energy Turret
        ///3310,Rapid Firing
        ///3311,Sharpshooter
        ///3312,Motion Prediction
        ///3315,Surgical Strike
        ///3316,Controlled Bursts
        ///3317,Traje [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string invTypes_Vanguard {
            get {
                return ResourceManager.GetString("invTypes_Vanguard", resourceCulture);
            }
        }
    }
}
